export const ROLL_DICE_REQUEST = 'ROLL_DICE_REQUEST'
export const ROLL_DICE_SUCCESS = 'ROLL_DICE_SUCCESS'
export const ROLL_DICE_FAIL = 'ROLL_DICE_FAIL'


export const CREATE_HISTORY_REQUEST = 'CREATE_HISTORY_REQUEST'
export const CREATE_HISTORY_SUCCESS = 'CREATE_HISTORY_SUCCESS'
export const CREATE_HISTORY_FAIL = 'CREATE_HISTORY_FAIL'

export const LIST_HISTORY_REQUEST = 'LIST_HISTORY_REQUEST'
export const LIST_HISTORY_SUCCESS = 'LIST_HISTORY_SUCCESS'
export const LIST_HISTORY_FAIL = 'LIST_HISTORY_FAIL'
