export const PROVABILITY_DETAIL_REQUEST = 'PROVABILITY_DETAIL_REQUEST'
export const PROVABILITY_DETAIL_SUCCESS = 'PROVABILITY_DETAIL_SUCCESS'
export const PROVABILITY_DETAIL_FAIL = 'PROVABILITY_DETAIL_FAIL'

export const PROVABILITY_CHANGE_REQUEST = 'PROVABILITY_CHANGE_REQUEST'
export const PROVABILITY_CHANGE_SUCCESS = 'PROVABILITY_CHANGE_SUCCESS'
export const PROVABILITY_CHANGE_FAIL = 'PROVABILITY_CHANGE_FAIL'
